
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
//import Header from "@/app/components/Header"
import Sidebar, { SidebarItem } from "@/app/components/Sidebar";
import "./globals.css";
import { FolderOpen ,BriefcaseBusiness,FolderClock,Settings,Store } from "lucide-react";
import Header from "./components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >        
        <div className="flex">
          <Sidebar>            
            <SidebarItem icon={<FolderClock size={20}/>} text="เอกสารรออนุมัติ" alert active count={2} path="./" />
            <SidebarItem icon={<BriefcaseBusiness size={20}/>} text="เอกสารของฉัน" alert count={1}/>
            <SidebarItem icon={<FolderOpen size={20}/>} text="เอกสารทั้งหมด" alert count={2}/>
            <hr className="my-3" />
            <SidebarItem icon={<Settings size={20}/>} text="ตั้งค่า"/>
            <SidebarItem icon={<Store size={20}/>} text="เกี่ยวกับเรา"/>
          </Sidebar>
          <main className="flex-1">
            <Header />
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
